export default [
  {
    id: '1',
    email: 'rick@example.com',
    firstName: 'Rick',
    lastName: 'Sanchez',
    createdAt: '1/12/1982',
    updatedAt: '1/12/1982',
    blogsAuthoredIds: ['1'],
    blogsContributedIds: ['2'],
  },
  {
    id: '2',
    email: 'steve@example.com',
    firstName: 'Morty',
    lastName: 'Smith',
    createdAt: '3/7/2016',
    updatedAt: '9/29/2017',
    blogsAuthoredIds: ['2'],
    blogsContributedIds: ['1'],
  },
  {
    id: '3',
    email: 'sarah@example.com',
    firstName: 'Summer',
    lastName: 'Smith',
    createdAt: '7/8/2017',
    updatedAt: null,
    blogsAuthoredIds: [],
    blogsContributedIds: ['1', '2'],
  },
  {
    id: '4',
    email: 'beth@example.com',
    firstName: 'Beth',
    lastName: 'Smith',
    createdAt: '4/5/2018',
    updatedAt: '4/7/2018',
    blogsAuthoredIds: [],
    blogsContributedIds: [],
  },
];
